version: '2'
services:
  master:
    image: elasticsearch:2
    ports:
      - "9200:9200"
    restart: always
    container_name: es_master
    links:
        - kibana:kibana
    depends_on:
      - kibana

  es-node1:
    image: elasticsearch:2
    command: elasticsearch --discovery.zen.ping.unicast.hosts=es_master
    restart: always
    container_name: es-node1
    environment:
      - "affinity:container!=*master*"
      - "affinity:container!=*es-node*"
    depends_on:
      - master
      - kibana
    links:
        - master:es_master
        - kibana:kibana

  kibana:
      image: kibana:4
      environment:
          - ELASTICSEARCH_URL=http://es_master:9200
      ports:
          - "5601:5601/tcp"
      container_name: kibana

